# Generated by Django 2.1.1 on 2019-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0003_auto_20190827_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='qstring',
            field=models.TextField(default='[]'),
        ),
    ]
