# Generated by Django 2.1.1 on 2019-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(default='', max_length=64)),
                ('question', models.TextField(default='')),
            ],
        ),
    ]
